-- T-007: business schema; run once via checksum-verified migration runner.

-- Never edit an applied migration. All references use NO ACTION; purge is explicit.

CREATE TABLE "organizations" (
  "id" INTEGER NOT NULL,
  "name" TEXT NOT NULL,
  "timezone" TEXT NOT NULL DEFAULT ('Asia/Bangkok'),
  "version" INTEGER NOT NULL DEFAULT (1),
  "created_at" TEXT NOT NULL DEFAULT (friday_now()),
  "updated_at" TEXT NOT NULL DEFAULT (friday_now()),
  CONSTRAINT "pk_organizations" PRIMARY KEY ("id"),
  CONSTRAINT "ck_organizations_id" CHECK ("id" = 1),
  CONSTRAINT "ck_organizations_name" CHECK (friday_utf16_units("name") BETWEEN 1 AND 100),
  CONSTRAINT "ck_organizations_timezone" CHECK ("timezone" IN ('Asia/Bangkok')),
  CONSTRAINT "ck_organizations_version" CHECK ("version" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_organizations_created_at" CHECK (friday_valid_utc("created_at") = 1),
  CONSTRAINT "ck_organizations_updated_at" CHECK (friday_valid_utc("updated_at") = 1)
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" TEXT NOT NULL,
  "display_name" TEXT NOT NULL,
  "password_hash" TEXT NOT NULL,
  "org_role" TEXT NOT NULL DEFAULT ('member'),
  "active" INTEGER NOT NULL DEFAULT (1),
  "must_change_password" INTEGER NOT NULL DEFAULT (1),
  "auth_version" INTEGER NOT NULL DEFAULT (1),
  "version" INTEGER NOT NULL DEFAULT (1),
  "created_at" TEXT NOT NULL DEFAULT (friday_now()),
  "updated_at" TEXT NOT NULL DEFAULT (friday_now()),
  "username_ci_key" TEXT GENERATED ALWAYS AS (friday_ci_key("username")) STORED NOT NULL,
  CONSTRAINT "ck_users_id" CHECK ("id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_users_username" CHECK (friday_utf16_units("username") BETWEEN 1 AND 60),
  CONSTRAINT "ck_users_display_name" CHECK (friday_utf16_units("display_name") BETWEEN 1 AND 100),
  CONSTRAINT "ck_users_password_hash" CHECK (friday_utf16_units("password_hash") BETWEEN 1 AND 1024),
  CONSTRAINT "ck_users_org_role" CHECK ("org_role" IN ('admin', 'member')),
  CONSTRAINT "ck_users_active" CHECK ("active" IN (0,1)),
  CONSTRAINT "ck_users_must_change_password" CHECK ("must_change_password" IN (0,1)),
  CONSTRAINT "ck_users_auth_version" CHECK ("auth_version" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_users_version" CHECK ("version" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_users_created_at" CHECK (friday_valid_utc("created_at") = 1),
  CONSTRAINT "ck_users_updated_at" CHECK (friday_valid_utc("updated_at") = 1),
  CONSTRAINT "ck_users_rule1" CHECK (username !~ '[^A-Za-z0-9._-]')
);

CREATE UNIQUE INDEX "uq_users_username" ON "users" ("username_ci_key");

CREATE INDEX "ix_users_active_org_role" ON "users" ("active", "org_role");

CREATE TABLE "sessions" (
  "token_hash" TEXT NOT NULL,
  "user_id" INTEGER NOT NULL,
  "csrf_token" TEXT NOT NULL,
  "auth_version" INTEGER NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT (friday_now()),
  "last_seen_at" TEXT NOT NULL DEFAULT (friday_now()),
  "absolute_expires_at" TEXT NOT NULL,
  CONSTRAINT "pk_sessions" PRIMARY KEY ("token_hash"),
  CONSTRAINT "ck_sessions_token_hash" CHECK (length("token_hash") = 64 AND "token_hash" !~ '[^0-9a-f]'),
  CONSTRAINT "ck_sessions_user_id" CHECK ("user_id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_sessions_csrf_token" CHECK (friday_utf16_units("csrf_token") BETWEEN 1 AND 128),
  CONSTRAINT "ck_sessions_auth_version" CHECK ("auth_version" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_sessions_created_at" CHECK (friday_valid_utc("created_at") = 1),
  CONSTRAINT "ck_sessions_last_seen_at" CHECK (friday_valid_utc("last_seen_at") = 1),
  CONSTRAINT "ck_sessions_absolute_expires_at" CHECK (friday_valid_utc("absolute_expires_at") = 1),
  CONSTRAINT "ck_sessions_rule1" CHECK (last_seen_at >= created_at AND absolute_expires_at > created_at AND last_seen_at < absolute_expires_at),
  CONSTRAINT "fk_sessions_1" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX "ix_sessions_user_id" ON "sessions" ("user_id");

CREATE INDEX "ix_sessions_absolute_expires_at" ON "sessions" ("absolute_expires_at");

CREATE INDEX "ix_sessions_last_seen_at" ON "sessions" ("last_seen_at");

CREATE TABLE "teams" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "description" TEXT NOT NULL DEFAULT (''),
  "archived_at" TEXT NULL,
  "version" INTEGER NOT NULL DEFAULT (1),
  "created_at" TEXT NOT NULL DEFAULT (friday_now()),
  "updated_at" TEXT NOT NULL DEFAULT (friday_now()),
  "name_ci_key" TEXT GENERATED ALWAYS AS (friday_ci_key("name")) STORED NOT NULL,
  CONSTRAINT "ck_teams_id" CHECK ("id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_teams_name" CHECK (friday_utf16_units("name") BETWEEN 1 AND 100),
  CONSTRAINT "ck_teams_description" CHECK (friday_utf16_units("description") BETWEEN 0 AND 1000),
  CONSTRAINT "ck_teams_archived_at" CHECK ("archived_at" IS NULL OR (friday_valid_utc("archived_at") = 1)),
  CONSTRAINT "ck_teams_version" CHECK ("version" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_teams_created_at" CHECK (friday_valid_utc("created_at") = 1),
  CONSTRAINT "ck_teams_updated_at" CHECK (friday_valid_utc("updated_at") = 1)
);

CREATE UNIQUE INDEX "uq_teams_name" ON "teams" ("name_ci_key");

CREATE TABLE "team_members" (
  "team_id" INTEGER NOT NULL,
  "user_id" INTEGER NOT NULL,
  "team_role" TEXT NOT NULL DEFAULT ('member'),
  "joined_at" TEXT NOT NULL DEFAULT (friday_now()),
  CONSTRAINT "pk_team_members" PRIMARY KEY ("team_id", "user_id"),
  CONSTRAINT "ck_team_members_team_id" CHECK ("team_id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_team_members_user_id" CHECK ("user_id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_team_members_team_role" CHECK ("team_role" IN ('lead', 'member')),
  CONSTRAINT "ck_team_members_joined_at" CHECK (friday_valid_utc("joined_at") = 1),
  CONSTRAINT "fk_team_members_1" FOREIGN KEY ("team_id") REFERENCES "teams" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_team_members_2" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX "ix_team_members_user_id" ON "team_members" ("user_id");

CREATE TABLE "projects" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_team_id" INTEGER NOT NULL,
  "name" TEXT NOT NULL,
  "description" TEXT NOT NULL DEFAULT (''),
  "archived_at" TEXT NULL,
  "version" INTEGER NOT NULL DEFAULT (1),
  "created_by" INTEGER NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT (friday_now()),
  "updated_at" TEXT NOT NULL DEFAULT (friday_now()),
  CONSTRAINT "ck_projects_id" CHECK ("id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_projects_owner_team_id" CHECK ("owner_team_id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_projects_name" CHECK (friday_utf16_units("name") BETWEEN 1 AND 100),
  CONSTRAINT "ck_projects_description" CHECK (friday_utf16_units("description") BETWEEN 0 AND 2000),
  CONSTRAINT "ck_projects_archived_at" CHECK ("archived_at" IS NULL OR (friday_valid_utc("archived_at") = 1)),
  CONSTRAINT "ck_projects_version" CHECK ("version" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_projects_created_by" CHECK ("created_by" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_projects_created_at" CHECK (friday_valid_utc("created_at") = 1),
  CONSTRAINT "ck_projects_updated_at" CHECK (friday_valid_utc("updated_at") = 1),
  CONSTRAINT "fk_projects_1" FOREIGN KEY ("owner_team_id") REFERENCES "teams" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_projects_2" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX "ix_projects_owner_team_id_archived_at" ON "projects" ("owner_team_id", "archived_at");

CREATE TABLE "project_members" (
  "project_id" INTEGER NOT NULL,
  "user_id" INTEGER NOT NULL,
  "access" TEXT NOT NULL,
  "added_by" INTEGER NOT NULL,
  "added_at" TEXT NOT NULL DEFAULT (friday_now()),
  CONSTRAINT "pk_project_members" PRIMARY KEY ("project_id", "user_id"),
  CONSTRAINT "ck_project_members_project_id" CHECK ("project_id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_project_members_user_id" CHECK ("user_id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_project_members_access" CHECK ("access" IN ('editor', 'viewer')),
  CONSTRAINT "ck_project_members_added_by" CHECK ("added_by" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_project_members_added_at" CHECK (friday_valid_utc("added_at") = 1),
  CONSTRAINT "fk_project_members_1" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_project_members_2" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_project_members_3" FOREIGN KEY ("added_by") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX "ix_project_members_user_id" ON "project_members" ("user_id");

CREATE TABLE "tasks" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" INTEGER NOT NULL,
  "title" TEXT NOT NULL,
  "description" TEXT NOT NULL DEFAULT (''),
  "category" TEXT NOT NULL DEFAULT (''),
  "status" TEXT NOT NULL DEFAULT ('todo'),
  "priority" TEXT NOT NULL DEFAULT ('medium'),
  "assignee_id" INTEGER NULL,
  "creator_id" INTEGER NOT NULL,
  "start_date" TEXT NULL,
  "due_date" TEXT NULL,
  "recurrence" TEXT NOT NULL DEFAULT ('none'),
  "recurrence_anchor_day" INTEGER NULL,
  "predecessor_task_id" INTEGER NULL,
  "successor_task_id" INTEGER NULL,
  "version" INTEGER NOT NULL DEFAULT (1),
  "created_at" TEXT NOT NULL DEFAULT (friday_now()),
  "updated_at" TEXT NOT NULL DEFAULT (friday_now()),
  "completed_at" TEXT NULL,
  "deleted_at" TEXT NULL,
  "deleted_by" INTEGER NULL,
  CONSTRAINT "ck_tasks_id" CHECK ("id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_tasks_project_id" CHECK ("project_id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_tasks_title" CHECK (friday_utf16_units("title") BETWEEN 1 AND 200),
  CONSTRAINT "ck_tasks_description" CHECK (friday_utf16_units("description") BETWEEN 0 AND 10000),
  CONSTRAINT "ck_tasks_category" CHECK (friday_utf16_units("category") BETWEEN 0 AND 80),
  CONSTRAINT "ck_tasks_status" CHECK ("status" IN ('todo', 'doing', 'blocked', 'done')),
  CONSTRAINT "ck_tasks_priority" CHECK ("priority" IN ('low', 'medium', 'high', 'urgent')),
  CONSTRAINT "ck_tasks_assignee_id" CHECK ("assignee_id" IS NULL OR ("assignee_id" BETWEEN 1 AND 2147483647)),
  CONSTRAINT "ck_tasks_creator_id" CHECK ("creator_id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_tasks_start_date" CHECK ("start_date" IS NULL OR (friday_valid_date("start_date") = 1)),
  CONSTRAINT "ck_tasks_due_date" CHECK ("due_date" IS NULL OR (friday_valid_date("due_date") = 1)),
  CONSTRAINT "ck_tasks_recurrence" CHECK ("recurrence" IN ('none', 'daily', 'weekly', 'monthly')),
  CONSTRAINT "ck_tasks_recurrence_anchor_day" CHECK ("recurrence_anchor_day" IS NULL OR ("recurrence_anchor_day" BETWEEN 1 AND 31)),
  CONSTRAINT "ck_tasks_predecessor_task_id" CHECK ("predecessor_task_id" IS NULL OR ("predecessor_task_id" BETWEEN 1 AND 2147483647)),
  CONSTRAINT "ck_tasks_successor_task_id" CHECK ("successor_task_id" IS NULL OR ("successor_task_id" BETWEEN 1 AND 2147483647)),
  CONSTRAINT "ck_tasks_version" CHECK ("version" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_tasks_created_at" CHECK (friday_valid_utc("created_at") = 1),
  CONSTRAINT "ck_tasks_updated_at" CHECK (friday_valid_utc("updated_at") = 1),
  CONSTRAINT "ck_tasks_completed_at" CHECK ("completed_at" IS NULL OR (friday_valid_utc("completed_at") = 1)),
  CONSTRAINT "ck_tasks_deleted_at" CHECK ("deleted_at" IS NULL OR (friday_valid_utc("deleted_at") = 1)),
  CONSTRAINT "ck_tasks_deleted_by" CHECK ("deleted_by" IS NULL OR ("deleted_by" BETWEEN 1 AND 2147483647)),
  CONSTRAINT "ck_tasks_rule1" CHECK (start_date IS NULL OR due_date IS NULL OR start_date <= due_date),
  CONSTRAINT "ck_tasks_rule2" CHECK (recurrence = 'none' OR due_date IS NOT NULL),
  CONSTRAINT "ck_tasks_rule3" CHECK ((recurrence = 'monthly' AND recurrence_anchor_day IS NOT NULL) OR (recurrence <> 'monthly' AND recurrence_anchor_day IS NULL)),
  CONSTRAINT "ck_tasks_rule4" CHECK ((status = 'done' AND completed_at IS NOT NULL) OR (status <> 'done' AND completed_at IS NULL)),
  CONSTRAINT "ck_tasks_rule5" CHECK ((deleted_at IS NULL AND deleted_by IS NULL) OR (deleted_at IS NOT NULL AND deleted_by IS NOT NULL)),
  CONSTRAINT "ck_tasks_rule6" CHECK (predecessor_task_id IS NULL OR predecessor_task_id <> id),
  CONSTRAINT "ck_tasks_rule7" CHECK (successor_task_id IS NULL OR successor_task_id <> id),
  CONSTRAINT "uq_tasks_identity_status" UNIQUE ("id", "project_id", "status"),
  CONSTRAINT "fk_tasks_1" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_tasks_2" FOREIGN KEY ("assignee_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_tasks_3" FOREIGN KEY ("creator_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_tasks_4" FOREIGN KEY ("deleted_by") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_tasks_5" FOREIGN KEY ("predecessor_task_id") REFERENCES "tasks" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_tasks_6" FOREIGN KEY ("successor_task_id") REFERENCES "tasks" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE UNIQUE INDEX "uq_tasks_predecessor_task_id" ON "tasks" ("predecessor_task_id") WHERE predecessor_task_id IS NOT NULL;

CREATE UNIQUE INDEX "uq_tasks_successor_task_id" ON "tasks" ("successor_task_id") WHERE successor_task_id IS NOT NULL;

CREATE INDEX "ix_tasks_project_id_status_deleted_at" ON "tasks" ("project_id", "status", "deleted_at");

CREATE INDEX "ix_tasks_assignee_id_due_date" ON "tasks" ("assignee_id", "due_date");

CREATE INDEX "ix_tasks_completed_at" ON "tasks" ("completed_at");

CREATE INDEX "ix_tasks_deleted_at" ON "tasks" ("deleted_at");

CREATE TABLE "subtasks" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "task_id" INTEGER NOT NULL,
  "title" TEXT NOT NULL,
  "done" INTEGER NOT NULL DEFAULT (0),
  "version" INTEGER NOT NULL DEFAULT (1),
  "created_at" TEXT NOT NULL DEFAULT (friday_now()),
  CONSTRAINT "ck_subtasks_id" CHECK ("id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_subtasks_task_id" CHECK ("task_id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_subtasks_title" CHECK (friday_utf16_units("title") BETWEEN 1 AND 200),
  CONSTRAINT "ck_subtasks_done" CHECK ("done" IN (0,1)),
  CONSTRAINT "ck_subtasks_version" CHECK ("version" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_subtasks_created_at" CHECK (friday_valid_utc("created_at") = 1),
  CONSTRAINT "fk_subtasks_1" FOREIGN KEY ("task_id") REFERENCES "tasks" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX "ix_subtasks_task_id_id" ON "subtasks" ("task_id", "id");

CREATE TABLE "board_columns" (
  "project_id" INTEGER NOT NULL,
  "status" TEXT NOT NULL,
  "version" INTEGER NOT NULL DEFAULT (1),
  CONSTRAINT "pk_board_columns" PRIMARY KEY ("project_id", "status"),
  CONSTRAINT "ck_board_columns_project_id" CHECK ("project_id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_board_columns_status" CHECK ("status" IN ('todo', 'doing', 'blocked', 'done')),
  CONSTRAINT "ck_board_columns_version" CHECK ("version" BETWEEN 1 AND 2147483647),
  CONSTRAINT "fk_board_columns_1" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE "board_positions" (
  "task_id" INTEGER NOT NULL,
  "project_id" INTEGER NOT NULL,
  "status" TEXT NOT NULL,
  "rank" INTEGER NOT NULL,
  CONSTRAINT "pk_board_positions" PRIMARY KEY ("task_id"),
  CONSTRAINT "ck_board_positions_task_id" CHECK ("task_id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_board_positions_project_id" CHECK ("project_id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_board_positions_status" CHECK ("status" IN ('todo', 'doing', 'blocked', 'done')),
  CONSTRAINT "ck_board_positions_rank" CHECK ("rank" BETWEEN -2147483648 AND 2147483647 AND "rank" <> 0),
  CONSTRAINT "fk_board_positions_1" FOREIGN KEY ("task_id", "project_id", "status") REFERENCES "tasks" ("id", "project_id", "status") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_board_positions_2" FOREIGN KEY ("project_id", "status") REFERENCES "board_columns" ("project_id", "status") ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE UNIQUE INDEX "uq_board_positions_project_id_status_rank" ON "board_positions" ("project_id", "status", "rank");

CREATE TABLE "comments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "task_id" INTEGER NOT NULL,
  "author_id" INTEGER NOT NULL,
  "body" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT (friday_now()),
  CONSTRAINT "ck_comments_id" CHECK ("id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_comments_task_id" CHECK ("task_id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_comments_author_id" CHECK ("author_id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_comments_body" CHECK (friday_utf16_units("body") BETWEEN 1 AND 5000),
  CONSTRAINT "ck_comments_created_at" CHECK (friday_valid_utc("created_at") = 1),
  CONSTRAINT "fk_comments_1" FOREIGN KEY ("task_id") REFERENCES "tasks" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_comments_2" FOREIGN KEY ("author_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX "ix_comments_task_id_id" ON "comments" ("task_id", "id");

CREATE TABLE "attachments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "task_id" INTEGER NOT NULL,
  "uploader_id" INTEGER NOT NULL,
  "original_name" TEXT NOT NULL,
  "storage_key" TEXT NOT NULL,
  "bytes" BIGINT NOT NULL,
  "validated_type" TEXT NOT NULL,
  "sha256" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT (friday_now()),
  "deleted_at" TEXT NULL,
  CONSTRAINT "ck_attachments_id" CHECK ("id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_attachments_task_id" CHECK ("task_id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_attachments_uploader_id" CHECK ("uploader_id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_attachments_original_name" CHECK (friday_utf16_units("original_name") BETWEEN 1 AND 200),
  CONSTRAINT "ck_attachments_storage_key" CHECK (friday_valid_uuid("storage_key") = 1),
  CONSTRAINT "ck_attachments_bytes" CHECK ("bytes" BETWEEN 1 AND 10485760),
  CONSTRAINT "ck_attachments_validated_type" CHECK (friday_utf16_units("validated_type") BETWEEN 1 AND 100),
  CONSTRAINT "ck_attachments_sha256" CHECK (length("sha256") = 64 AND "sha256" !~ '[^0-9a-f]'),
  CONSTRAINT "ck_attachments_created_at" CHECK (friday_valid_utc("created_at") = 1),
  CONSTRAINT "ck_attachments_deleted_at" CHECK ("deleted_at" IS NULL OR (friday_valid_utc("deleted_at") = 1)),
  CONSTRAINT "fk_attachments_1" FOREIGN KEY ("task_id") REFERENCES "tasks" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_attachments_2" FOREIGN KEY ("uploader_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE UNIQUE INDEX "uq_attachments_storage_key" ON "attachments" ("storage_key");

CREATE INDEX "ix_attachments_task_id_id" ON "attachments" ("task_id", "id");

CREATE INDEX "ix_attachments_deleted_at" ON "attachments" ("deleted_at");

CREATE TABLE "task_events" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "task_id" INTEGER NOT NULL,
  "actor_id" INTEGER NULL,
  "action" TEXT NOT NULL,
  "field_changes" TEXT NOT NULL,
  "request_id" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT (friday_now()),
  CONSTRAINT "ck_task_events_id" CHECK ("id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_task_events_task_id" CHECK ("task_id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_task_events_actor_id" CHECK ("actor_id" IS NULL OR ("actor_id" BETWEEN 1 AND 2147483647)),
  CONSTRAINT "ck_task_events_action" CHECK ("action" IN ('created', 'updated', 'assigned', 'status_changed', 'reopened', 'deleted', 'restored', 'subtask_changed', 'comment_added', 'attachment_changed', 'reordered', 'recurrence_generated', 'access_cleanup')),
  CONSTRAINT "ck_task_events_field_changes" CHECK (json_valid("field_changes") = 1 AND json_type("field_changes") = 'array'),
  CONSTRAINT "ck_task_events_request_id" CHECK (friday_valid_uuid("request_id") = 1),
  CONSTRAINT "ck_task_events_created_at" CHECK (friday_valid_utc("created_at") = 1),
  CONSTRAINT "fk_task_events_1" FOREIGN KEY ("task_id") REFERENCES "tasks" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_task_events_2" FOREIGN KEY ("actor_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX "ix_task_events_task_id_id" ON "task_events" ("task_id", "id");

CREATE TABLE "admin_events" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "actor_id" INTEGER NOT NULL,
  "action" TEXT NOT NULL,
  "resource_type" TEXT NOT NULL,
  "resource_id" INTEGER NULL,
  "redacted_changes" TEXT NOT NULL,
  "request_id" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT (friday_now()),
  CONSTRAINT "ck_admin_events_id" CHECK ("id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_admin_events_actor_id" CHECK ("actor_id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_admin_events_action" CHECK (friday_utf16_units("action") BETWEEN 1 AND 100),
  CONSTRAINT "ck_admin_events_resource_type" CHECK (friday_utf16_units("resource_type") BETWEEN 1 AND 100),
  CONSTRAINT "ck_admin_events_resource_id" CHECK ("resource_id" IS NULL OR ("resource_id" BETWEEN 1 AND 2147483647)),
  CONSTRAINT "ck_admin_events_redacted_changes" CHECK (json_valid("redacted_changes") = 1 AND json_type("redacted_changes") IN ('object','array')),
  CONSTRAINT "ck_admin_events_request_id" CHECK (friday_valid_uuid("request_id") = 1),
  CONSTRAINT "ck_admin_events_created_at" CHECK (friday_valid_utc("created_at") = 1),
  CONSTRAINT "fk_admin_events_1" FOREIGN KEY ("actor_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX "ix_admin_events_created_at_id" ON "admin_events" ("created_at", "id");

CREATE TABLE "notifications" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "recipient_id" INTEGER NOT NULL,
  "task_id" INTEGER NOT NULL,
  "type" TEXT NOT NULL,
  "message" TEXT NOT NULL,
  "dedupe_key" TEXT NOT NULL,
  "read_at" TEXT NULL,
  "created_at" TEXT NOT NULL DEFAULT (friday_now()),
  CONSTRAINT "ck_notifications_id" CHECK ("id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_notifications_recipient_id" CHECK ("recipient_id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_notifications_task_id" CHECK ("task_id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_notifications_type" CHECK ("type" IN ('assignment', 'comment', 'status', 'access_cleanup', 'due_tomorrow', 'due_today', 'overdue')),
  CONSTRAINT "ck_notifications_message" CHECK (friday_utf16_units("message") BETWEEN 1 AND 500),
  CONSTRAINT "ck_notifications_dedupe_key" CHECK (friday_utf16_units("dedupe_key") BETWEEN 1 AND 300),
  CONSTRAINT "ck_notifications_read_at" CHECK ("read_at" IS NULL OR (friday_valid_utc("read_at") = 1)),
  CONSTRAINT "ck_notifications_created_at" CHECK (friday_valid_utc("created_at") = 1),
  CONSTRAINT "fk_notifications_1" FOREIGN KEY ("recipient_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_notifications_2" FOREIGN KEY ("task_id") REFERENCES "tasks" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE UNIQUE INDEX "uq_notifications_dedupe_key" ON "notifications" ("dedupe_key");

CREATE INDEX "ix_notifications_recipient_id_read_at" ON "notifications" ("recipient_id", "read_at");

CREATE INDEX "ix_notifications_created_at" ON "notifications" ("created_at");

CREATE INDEX "ix_notifications_task_id" ON "notifications" ("task_id");

CREATE TABLE "recurrence_events" (
  "source_task_id" INTEGER NOT NULL,
  "generated_task_id" INTEGER NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT (friday_now()),
  CONSTRAINT "pk_recurrence_events" PRIMARY KEY ("source_task_id"),
  CONSTRAINT "ck_recurrence_events_source_task_id" CHECK ("source_task_id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_recurrence_events_generated_task_id" CHECK ("generated_task_id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_recurrence_events_created_at" CHECK (friday_valid_utc("created_at") = 1),
  CONSTRAINT "ck_recurrence_events_rule1" CHECK (source_task_id <> generated_task_id)
);

CREATE UNIQUE INDEX "uq_recurrence_events_generated_task_id" ON "recurrence_events" ("generated_task_id");

CREATE TABLE "idempotency_keys" (
  "user_id" INTEGER NOT NULL,
  "route" TEXT NOT NULL,
  "key" TEXT NOT NULL,
  "request_hash" TEXT NOT NULL,
  "response_status" INTEGER NOT NULL,
  "response_body" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT (friday_now()),
  "expires_at" TEXT NOT NULL,
  CONSTRAINT "pk_idempotency_keys" PRIMARY KEY ("user_id", "route", "key"),
  CONSTRAINT "ck_idempotency_keys_user_id" CHECK ("user_id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_idempotency_keys_route" CHECK (friday_utf16_units("route") BETWEEN 1 AND 256),
  CONSTRAINT "ck_idempotency_keys_key" CHECK (friday_valid_uuid("key") = 1),
  CONSTRAINT "ck_idempotency_keys_request_hash" CHECK (length("request_hash") = 64 AND "request_hash" !~ '[^0-9a-f]'),
  CONSTRAINT "ck_idempotency_keys_response_status" CHECK ("response_status" BETWEEN 100 AND 599),
  CONSTRAINT "ck_idempotency_keys_response_body" CHECK (json_valid("response_body") = 1 AND json_type("response_body") IN ('object','array')),
  CONSTRAINT "ck_idempotency_keys_created_at" CHECK (friday_valid_utc("created_at") = 1),
  CONSTRAINT "ck_idempotency_keys_expires_at" CHECK (friday_valid_utc("expires_at") = 1),
  CONSTRAINT "ck_idempotency_keys_rule1" CHECK (expires_at > created_at),
  CONSTRAINT "fk_idempotency_keys_1" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX "ix_idempotency_keys_expires_at" ON "idempotency_keys" ("expires_at");

CREATE TABLE "user_view_revisions" (
  "user_id" INTEGER NOT NULL,
  "revision" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL DEFAULT (friday_now()),
  CONSTRAINT "pk_user_view_revisions" PRIMARY KEY ("user_id"),
  CONSTRAINT "ck_user_view_revisions_user_id" CHECK ("user_id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_user_view_revisions_revision" CHECK (friday_valid_uuid("revision") = 1),
  CONSTRAINT "ck_user_view_revisions_updated_at" CHECK (friday_valid_utc("updated_at") = 1),
  CONSTRAINT "fk_user_view_revisions_1" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE "storage_quota" (
  "id" INTEGER NOT NULL,
  "stored_bytes" BIGINT NOT NULL DEFAULT (0),
  "reserved_bytes" BIGINT NOT NULL DEFAULT (0),
  CONSTRAINT "pk_storage_quota" PRIMARY KEY ("id"),
  CONSTRAINT "ck_storage_quota_id" CHECK ("id" = 1),
  CONSTRAINT "ck_storage_quota_stored_bytes" CHECK ("stored_bytes" BETWEEN 0 AND 9007199254740991),
  CONSTRAINT "ck_storage_quota_reserved_bytes" CHECK ("reserved_bytes" BETWEEN 0 AND 9007199254740991),
  CONSTRAINT "ck_storage_quota_rule1" CHECK (stored_bytes <= 9007199254740991 - reserved_bytes)
);

CREATE TABLE "upload_reservations" (
  "id" TEXT NOT NULL,
  "user_id" INTEGER NOT NULL,
  "task_id" INTEGER NOT NULL,
  "reserved_bytes" BIGINT NOT NULL,
  "actual_bytes" BIGINT NULL,
  "temp_key" TEXT NOT NULL,
  "storage_key" TEXT NULL,
  "created_at" TEXT NOT NULL DEFAULT (friday_now()),
  "expires_at" TEXT NOT NULL,
  "phase" TEXT NOT NULL DEFAULT ('receiving'),
  CONSTRAINT "pk_upload_reservations" PRIMARY KEY ("id"),
  CONSTRAINT "ck_upload_reservations_id" CHECK (friday_valid_uuid("id") = 1),
  CONSTRAINT "ck_upload_reservations_user_id" CHECK ("user_id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_upload_reservations_task_id" CHECK ("task_id" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_upload_reservations_reserved_bytes" CHECK ("reserved_bytes" BETWEEN 1 AND 10485760),
  CONSTRAINT "ck_upload_reservations_actual_bytes" CHECK ("actual_bytes" IS NULL OR ("actual_bytes" BETWEEN 1 AND 10485760)),
  CONSTRAINT "ck_upload_reservations_temp_key" CHECK (friday_valid_uuid("temp_key") = 1),
  CONSTRAINT "ck_upload_reservations_storage_key" CHECK ("storage_key" IS NULL OR (friday_valid_uuid("storage_key") = 1)),
  CONSTRAINT "ck_upload_reservations_created_at" CHECK (friday_valid_utc("created_at") = 1),
  CONSTRAINT "ck_upload_reservations_expires_at" CHECK (friday_valid_utc("expires_at") = 1),
  CONSTRAINT "ck_upload_reservations_phase" CHECK ("phase" IN ('receiving', 'validated', 'finalizing')),
  CONSTRAINT "ck_upload_reservations_rule1" CHECK (actual_bytes IS NULL OR actual_bytes <= reserved_bytes),
  CONSTRAINT "ck_upload_reservations_rule2" CHECK (phase = 'receiving' OR actual_bytes IS NOT NULL),
  CONSTRAINT "ck_upload_reservations_rule3" CHECK (phase <> 'finalizing' OR storage_key IS NOT NULL),
  CONSTRAINT "ck_upload_reservations_rule4" CHECK (expires_at > created_at),
  CONSTRAINT "fk_upload_reservations_1" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_upload_reservations_2" FOREIGN KEY ("task_id") REFERENCES "tasks" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE UNIQUE INDEX "uq_upload_reservations_temp_key" ON "upload_reservations" ("temp_key");

CREATE UNIQUE INDEX "uq_upload_reservations_storage_key" ON "upload_reservations" ("storage_key") WHERE storage_key IS NOT NULL;

CREATE INDEX "ix_upload_reservations_expires_at_phase" ON "upload_reservations" ("expires_at", "phase");

CREATE INDEX "ix_upload_reservations_task_id" ON "upload_reservations" ("task_id");

CREATE TABLE "file_cleanup_queue" (
  "storage_key" TEXT NOT NULL,
  "bytes" BIGINT NOT NULL,
  "reason" TEXT NOT NULL,
  "attempts" INTEGER NOT NULL DEFAULT (0),
  "created_at" TEXT NOT NULL DEFAULT (friday_now()),
  "next_attempt_at" TEXT NOT NULL DEFAULT (friday_now()),
  CONSTRAINT "pk_file_cleanup_queue" PRIMARY KEY ("storage_key"),
  CONSTRAINT "ck_file_cleanup_queue_storage_key" CHECK (friday_valid_uuid("storage_key") = 1),
  CONSTRAINT "ck_file_cleanup_queue_bytes" CHECK ("bytes" BETWEEN 1 AND 10485760),
  CONSTRAINT "ck_file_cleanup_queue_reason" CHECK (friday_utf16_units("reason") BETWEEN 1 AND 100),
  CONSTRAINT "ck_file_cleanup_queue_attempts" CHECK ("attempts" BETWEEN 0 AND 2147483647),
  CONSTRAINT "ck_file_cleanup_queue_created_at" CHECK (friday_valid_utc("created_at") = 1),
  CONSTRAINT "ck_file_cleanup_queue_next_attempt_at" CHECK (friday_valid_utc("next_attempt_at") = 1)
);

CREATE INDEX "ix_file_cleanup_queue_next_attempt_at" ON "file_cleanup_queue" ("next_attempt_at");

CREATE TABLE "maintenance_state" (
  "id" INTEGER NOT NULL,
  "owner_id" TEXT NOT NULL,
  "state" TEXT NOT NULL,
  "lease_expires_at" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT (friday_now()),
  "updated_at" TEXT NOT NULL DEFAULT (friday_now()),
  CONSTRAINT "pk_maintenance_state" PRIMARY KEY ("id"),
  CONSTRAINT "ck_maintenance_state_id" CHECK ("id" = 1),
  CONSTRAINT "ck_maintenance_state_owner_id" CHECK (friday_valid_uuid("owner_id") = 1),
  CONSTRAINT "ck_maintenance_state_state" CHECK ("state" IN ('entering', 'frozen', 'leaving')),
  CONSTRAINT "ck_maintenance_state_lease_expires_at" CHECK (friday_valid_utc("lease_expires_at") = 1),
  CONSTRAINT "ck_maintenance_state_created_at" CHECK (friday_valid_utc("created_at") = 1),
  CONSTRAINT "ck_maintenance_state_updated_at" CHECK (friday_valid_utc("updated_at") = 1),
  CONSTRAINT "ck_maintenance_state_rule1" CHECK (lease_expires_at > updated_at)
);

CREATE TABLE "rate_limit_buckets" (
  "kind" TEXT NOT NULL,
  "bucket_hash" TEXT NOT NULL,
  "window_started_at" TEXT NOT NULL,
  "window_expires_at" TEXT NOT NULL,
  "attempts" INTEGER NOT NULL DEFAULT (0),
  CONSTRAINT "pk_rate_limit_buckets" PRIMARY KEY ("kind", "bucket_hash", "window_started_at"),
  CONSTRAINT "ck_rate_limit_buckets_kind" CHECK (friday_utf16_units("kind") BETWEEN 1 AND 30),
  CONSTRAINT "ck_rate_limit_buckets_bucket_hash" CHECK (length("bucket_hash") = 64 AND "bucket_hash" !~ '[^0-9a-f]'),
  CONSTRAINT "ck_rate_limit_buckets_window_started_at" CHECK (friday_valid_utc("window_started_at") = 1),
  CONSTRAINT "ck_rate_limit_buckets_window_expires_at" CHECK (friday_valid_utc("window_expires_at") = 1),
  CONSTRAINT "ck_rate_limit_buckets_attempts" CHECK ("attempts" BETWEEN 0 AND 2147483647),
  CONSTRAINT "ck_rate_limit_buckets_rule1" CHECK (window_expires_at > window_started_at)
);

CREATE INDEX "ix_rate_limit_buckets_window_expires_at" ON "rate_limit_buckets" ("window_expires_at");

INSERT INTO storage_quota (id,stored_bytes,reserved_bytes) VALUES (1,0,0);
