-- T-084 FR-48 project docs, T-085 FR-49 project-level files (shared quota/validation/cleanup).
CREATE TABLE "project_docs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" INTEGER NOT NULL,
  "title" TEXT NOT NULL,
  "body_html" TEXT NOT NULL DEFAULT (''),
  "text_length" INTEGER NOT NULL DEFAULT (0),
  "version" INTEGER NOT NULL DEFAULT (1),
  "created_by" INTEGER NOT NULL,
  "updated_by" INTEGER NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "deleted_at" TEXT NULL,
  "deleted_by" INTEGER NULL,
  CONSTRAINT "ck_project_docs_title" CHECK (friday_utf16_units(trim("title")) BETWEEN 1 AND 200),
  CONSTRAINT "ck_project_docs_body" CHECK (length("body_html") <= 1000000),
  CONSTRAINT "ck_project_docs_text_length" CHECK ("text_length" BETWEEN 0 AND 200000),
  CONSTRAINT "ck_project_docs_version" CHECK ("version" BETWEEN 1 AND 2147483647),
  CONSTRAINT "ck_project_docs_created_at" CHECK (friday_valid_utc("created_at") = 1),
  CONSTRAINT "ck_project_docs_updated_at" CHECK (friday_valid_utc("updated_at") = 1),
  CONSTRAINT "ck_project_docs_deleted_at" CHECK ("deleted_at" IS NULL OR (friday_valid_utc("deleted_at") = 1)),
  CONSTRAINT "ck_project_docs_deleted_pair" CHECK (("deleted_at" IS NULL) = ("deleted_by" IS NULL)),
  CONSTRAINT "fk_project_docs_1" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_project_docs_2" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_project_docs_3" FOREIGN KEY ("updated_by") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_project_docs_4" FOREIGN KEY ("deleted_by") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE INDEX "ix_project_docs_project" ON "project_docs" ("project_id", "deleted_at", "id");
CREATE TABLE "project_doc_versions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "doc_id" INTEGER NOT NULL,
  "version" INTEGER NOT NULL,
  "title" TEXT NOT NULL,
  "body_html" TEXT NOT NULL,
  "edited_by" INTEGER NOT NULL,
  "edited_at" TEXT NOT NULL,
  CONSTRAINT "ck_project_doc_versions_edited_at" CHECK (friday_valid_utc("edited_at") = 1),
  CONSTRAINT "fk_project_doc_versions_1" FOREIGN KEY ("doc_id") REFERENCES "project_docs" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_project_doc_versions_2" FOREIGN KEY ("edited_by") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE UNIQUE INDEX "uq_project_doc_versions" ON "project_doc_versions" ("doc_id", "version");
CREATE TABLE "project_files" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" INTEGER NOT NULL,
  "uploader_id" INTEGER NOT NULL,
  "original_name" TEXT NOT NULL,
  "storage_key" TEXT NOT NULL,
  "bytes" INTEGER NOT NULL,
  "validated_type" TEXT NOT NULL,
  "sha256" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "deleted_at" TEXT NULL,
  CONSTRAINT "ck_project_files_original_name" CHECK (friday_utf16_units("original_name") BETWEEN 1 AND 200),
  CONSTRAINT "ck_project_files_storage_key" CHECK (friday_valid_uuid("storage_key") = 1),
  CONSTRAINT "ck_project_files_bytes" CHECK ("bytes" BETWEEN 1 AND 10485760),
  CONSTRAINT "ck_project_files_validated_type" CHECK (friday_utf16_units("validated_type") BETWEEN 1 AND 100),
  CONSTRAINT "ck_project_files_sha256" CHECK (length("sha256") = 64 AND "sha256" !~ '[^0-9a-f]'),
  CONSTRAINT "ck_project_files_created_at" CHECK (friday_valid_utc("created_at") = 1),
  CONSTRAINT "ck_project_files_deleted_at" CHECK ("deleted_at" IS NULL OR (friday_valid_utc("deleted_at") = 1)),
  CONSTRAINT "fk_project_files_1" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_project_files_2" FOREIGN KEY ("uploader_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE UNIQUE INDEX "uq_project_files_storage_key" ON "project_files" ("storage_key");
CREATE INDEX "ix_project_files_project" ON "project_files" ("project_id", "id");
-- SQLite cannot relax NOT NULL; rebuild reservations so a reservation targets one task or one project.
-- Project-level uploads: task_id becomes optional and project_id is added (SQLite rebuilds the
-- table; PostgreSQL alters it in place, keeping existing indexes).
ALTER TABLE "upload_reservations" ALTER COLUMN "task_id" DROP NOT NULL;
ALTER TABLE "upload_reservations" ADD COLUMN "project_id" INTEGER NULL;
ALTER TABLE "upload_reservations" DROP CONSTRAINT "ck_upload_reservations_task_id";
ALTER TABLE "upload_reservations" ADD CONSTRAINT "ck_upload_reservations_task_id" CHECK ("task_id" IS NULL OR ("task_id" BETWEEN 1 AND 2147483647));
ALTER TABLE "upload_reservations" ADD CONSTRAINT "ck_upload_reservations_target" CHECK (("task_id" IS NULL) <> ("project_id" IS NULL));
ALTER TABLE "upload_reservations" ADD CONSTRAINT "fk_upload_reservations_3" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
